In [1]:
import pandas as pd
import warnings
import cudf
import cupy as cp
warnings.filterwarnings("ignore", category=UserWarning)
warnings.filterwarnings("ignore", category=FutureWarning)

## 5 Cross Validation Sampling

In [2]:
data_prep = pd.read_csv("/kaggle/input/datasets/deskafimcode/dataset-training/data_clean_review.csv")
data_prep.head()

                                        clean_review
0  enjoyed first season must say think season eve...
1  know iceland small country police thing bit di...
2  except k k actor look comfortable acting fight...
3  im guessing year old white woman im target dem...
4  here truth there much movie sucked high rating...

In [3]:
data_sampling = pd.read_csv("/kaggle/input/datasets/deskafimcode/dataset-training/data_sampling_labelbagging.csv")
data_sampling.head()

,review_id,movie,rating,review_detail,label_komen
0,rw5704482,After Life (2019– ),9.0,"I enjoyed the first season, but I must say I t...",1
1,rw5704483,The Valhalla Murders (2019– ),6.0,I know Iceland is a small country and police d...,0
2,rw5704484,Special OPS (2020– ),7.0,"Except K K , no other actor looks comfortable ...",0
3,rw5704485,#BlackAF (2020– ),8.0,I'm guessing that as a 62 year old white woman...,1
4,rw5704487,The Droving (2020),2.0,Here's the truth. There's not much to this mov...,0

In [4]:
data_sampling["clean_review"] = data_prep["clean_review"]
data_sampling.head()

,review_id,movie,rating,review_detail,label_komen,clean_review
0,rw5704482,After Life (2019– ),9.0,"I enjoyed the first season, but I must say I t...",1,enjoyed first season must say think season eve...
1,rw5704483,The Valhalla Murders (2019– ),6.0,I know Iceland is a small country and police d...,0,know iceland small country police thing bit di...
2,rw5704484,Special OPS (2020– ),7.0,"Except K K , no other actor looks comfortable ...",0,except k k actor look comfortable acting fight...
3,rw5704485,#BlackAF (2020– ),8.0,I'm guessing that as a 62 year old white woman...,1,im guessing year old white woman im target dem...
4,rw5704487,The Droving (2020),2.0,Here's the truth. There's not much to this mov...,0,here truth there much movie sucked high rating...

### Imbalance per Batch

In [5]:
d_data = data_sampling.to_dict(orient="list")

In [6]:
data_5_val = [{"clean_review" : [] , "label_komen" : []},{"clean_review" : [], "label_komen" : []},{"clean_review" : [], "label_komen" : []},{"clean_review" : [], "label_komen" : []},{"clean_review" : [], "label_komen" : []}]

counter = 0

for j in data_5_val :
    for k in range(data_sampling.shape[0] // 5) :
        j["clean_review"].append(d_data["clean_review"][counter])
        j["label_komen"].append(d_data["label_komen"][counter])
        counter+=1
else :
    for k in range(data_sampling.shape[0] % 5) :
        data_5_val[k]["clean_review"].append(d_data["clean_review"][counter])
        data_5_val[k]["label_komen"].append(d_data["label_komen"][counter])
        counter+=1

In [7]:
summ = 0
for i in data_5_val :
    summ += len(i["clean_review"])
summ

295357

In [8]:
for i in range(len(data_5_val)) :
    data_5_val[i] = cudf.DataFrame(data_5_val[i])

### Balance per Batch

In [9]:
data01terpisah = {"pos" : {"clean_review" : [], "label_komen" : []}, "neg" : {"clean_review" : [], "label_komen" : []}}
summm = {"pos" : 0, "neg" : 0}
for i in range(data_sampling.shape[0]) :
    if d_data["label_komen"][i] == 0 :
        data01terpisah["neg"]["clean_review"].append(d_data["clean_review"][i])
        data01terpisah["neg"]["label_komen"].append(d_data["label_komen"][i])
        summm["neg"] += 1
    else :
        data01terpisah["pos"]["clean_review"].append(d_data["clean_review"][i])
        data01terpisah["pos"]["label_komen"].append(d_data["label_komen"][i])
        summm["pos"] += 1
        
print(summm)

{'pos': 172766, 'neg': 122591}

In [10]:
data_5_val2 = [{"clean_review" : [] , "label_komen" : []},{"clean_review" : [], "label_komen" : []},{"clean_review" : [], "label_komen" : []},{"clean_review" : [], "label_komen" : []},{"clean_review" : [], "label_komen" : []}]

counter = 0
for j in data_5_val2 :
    for k in range(summm["pos"] // 5) :
        j["clean_review"].append(data01terpisah["pos"]["clean_review"][counter])
        j["label_komen"].append(data01terpisah["pos"]["label_komen"][counter])
        counter+=1
else :
    for k in range(summm["pos"] % 5) :
        j["clean_review"].append(data01terpisah["pos"]["clean_review"][counter])
        j["label_komen"].append(data01terpisah["pos"]["label_komen"][counter])
        counter+=1
        
counter = 0
for j in data_5_val2 :
    for k in range(summm["neg"] // 5) :
        j["clean_review"].append(data01terpisah["neg"]["clean_review"][counter])
        j["label_komen"].append(data01terpisah["neg"]["label_komen"][counter])
        counter+=1
else :
    for k in range(summm["neg"] % 5) :
        j["clean_review"].append(data01terpisah["neg"]["clean_review"][counter])
        j["label_komen"].append(data01terpisah["neg"]["label_komen"][counter])
        counter+=1

In [11]:
summ = 0
for i in data_5_val2 :
    summ += len(i["clean_review"])
summ

295357

In [12]:
for i in range(len(data_5_val2)) :
    data_5_val2[i] = cudf.DataFrame(data_5_val2[i])

## LETSGOOO GRID SEARCHHHH!!!!

### Penjelasan Parameter Training

model_nb_tuned = MultinomialNB(

    alpha=0.1          # Smoothing parameter: Membantu mengatasi masalah kata yang tidak ada di data training.

                       # Catatan: cuML MultinomialNB belum mendukung parameter fit_prior seperti scikit-learn.

)

model_lr_tuned = LogisticRegression(

    C=2.0,              # Regularisasi: Nilai lebih kecil = regularisasi kuat (mencegah overfitting). 
    
                        # Nilai lebih besar = model lebih fitting ke data training.
    
    solver='qn',        # Algoritma optimasi: 'qn' (Quasi-Newton/L-BFGS) adalah default di cuML yang sangat cepat 
    
                        # memanfaatkan GPU. cuML belum menyediakan solver 'saga'.
    
    max_iter=1000,      # Jumlah iterasi maksimum: Batas iterasi optimasi. Naikkan jika model belum konvergen.
    
    linesearch_max_iter=50 # Parameter khusus cuML: Batas iterasi pencarian jalur optimasi untuk menstabilkan solver 'qn'.

)

model_svm_tuned = LinearSVC(

    C=1.0,              # Penalti regularisasi: Mengontrol keseimbangan antara margin yang lebar dan meminimalkan kesalahan klasifikasi.

    loss='squared_hinge', # Fungsi loss: Fungsi penalti standar untuk LinearSVC.

    max_iter=2000,      # Batas iterasi: Ditargetkan agar kalkulasi pada data besar selesai dengan sempurna di GPU.

    fit_intercept=True  # Menentukan apakah bias/intercept perlu dihitung (secara default True di scikit-learn).

                        # Catatan: cuML LinearSVC tidak memerlukan parameter random_state karena sifat optimisasinya di GPU.

)


model_rf_tuned = RandomForestClassifier(

    n_estimators=200,      # Jumlah pohon keputusan: Lebih banyak pohon = lebih stabil dan akurat. Di GPU prosesnya akan tetap instan.

    max_depth=20,          # Kedalaman maksimum pohon: Membatasi kompleksitas pohon agar tidak overfitting dan hemat memori GPU.

    min_samples_split=5,   # Sampel minimum untuk split: Jumlah sampel minimal di sebuah node sebelum dipecah menjadi cabang baru.

    n_bins=15,             # Parameter khusus cuML: Jumlah bin diskritisasi untuk fitur kontinu. cuML menggunakan ini 

                           # untuk mempercepat kalkulasi split di GPU secara signifikan.

    random_state=42        # Konsistensi hasil: Memastikan pembuatan pohon menghasilkan hasil yang sama setiap kali dijalankan.

                           # Catatan: Parameter n_jobs=-1 dihapus karena cuML secara otomatis menggunakan seluruh core paralel GPU.
)

### Training

In [13]:
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler
from imblearn.combine import SMOTEENN, SMOTETomek

from cuml.naive_bayes import MultinomialNB
from cuml.linear_model import LogisticRegression
from cuml.svm import LinearSVC
from cuml.ensemble import RandomForestClassifier

from cuml.feature_extraction.text import TfidfVectorizer
import heapq as hq
from cuml.metrics import accuracy_score
import gc

class kombinasi_stack :
    paket_data = None
    tf_idf_model = None
    imbalancer = None
    base_model_1 = None
    base_model_2 = None
    base_model_3 = None
    meta_model = None
    
    def __init__(self,paket_data,tf_idf_model,imbalancer,base_model_1,base_model_2,base_model_3,meta_model):
        self.paket_data = paket_data
        self.tf_idf_model = tf_idf_model
        self.imbalancer = imbalancer
        self.base_model_1 = base_model_1
        self.base_model_2 = base_model_2
        self.base_model_3 = base_model_3
        self.meta_model = meta_model

In [14]:
# data_5_batch = {"Imbalance" : data_5_val, "Balance" : data_5_val2}

# list_imbalancer = {
#     "Tanpa Imbalancer" : None,
#     "Smote" : SMOTE(random_state=42),
#     "Random Under Sampler" : RandomUnderSampler(random_state=42)
# }

# tuning_tfidf = {"ngram_range": [(1, 1), (1, 2)],"max_features": [10000],"max_df": [0.9],"min_df": [0.01], "binary": [False]}
# tuning_nb = {"alpha" : [0.01, 0.1, 0.5, 1.0, 5.0, 10.0]}
# tuning_svm = {"C": [0.1, 1, 10], "loss" : ["squared_hinge","hinge"], "max_iter" : [1000, 2000], "fit_intercept" : [True, False]}
# tuning_rf = {"n_estimators" : [100, 200], "max_depth" : [12, 16], "min_samples_leaf" : [3,5], "n_bins" : [15, 32, 64]}
# tuning_lr = {"C" : [0.01, 0.1], "penalty" : ["l1", "l2"], "max_iter" : [100, 500], "linesearch_max_iter" : [50, 100]}

# qiu_primer = []
# counter = 0
# z_counter = 0
# total_gridsearch = len(data_5_batch) * 5 * len(list_imbalancer) * len(tuning_tfidf["ngram_range"]) * len(tuning_tfidf["max_features"]) * len(tuning_tfidf["max_df"]) * len(tuning_tfidf["min_df"]) * len(tuning_tfidf["binary"])
# for h in data_5_batch:                                                                                          # 2
#     paket_data = data_5_batch[h]
#     # for i in range(len(paket_data)):                                                                            # 5
#         train = cudf.DataFrame({"clean_review" : [], "label_komen" : []})
#         test = cudf.DataFrame({"clean_review" : [], "label_komen" : []})
#         batch_data_test = i
        
#         for j in range(len(paket_data)):
#             if j == i:
#                 test = cudf.concat([test, paket_data[j]], axis=0, ignore_index=True)
#             else:
#                 train = cudf.concat([train, paket_data[j]], axis=0, ignore_index=True)
        
#         train['clean_review'] = train['clean_review'].fillna('')
#         test['clean_review'] = test['clean_review'].fillna('')
        
#         for a in tuning_tfidf["ngram_range"] :                                                                  # 3
#             for b in tuning_tfidf["max_features"] :
#                 for c in tuning_tfidf["max_df"] :
#                     for d in tuning_tfidf["min_df"] :
#                         for e in tuning_tfidf["binary"] :
                            
#                             tfidf_vectorizer = TfidfVectorizer(ngram_range= a,max_features= b,max_df= c,min_df= d,binary= e)
#                             x_train_awal = tfidf_vectorizer.fit_transform(train['clean_review'])
#                             x_test = tfidf_vectorizer.transform(test["clean_review"])
                            
#                             y_train_awal = train["label_komen"]
#                             y_test = test["label_komen"]
                            
#                             tfidf = (tfidf_vectorizer, f"TfidfVectorizer(ngram_range = {a},max_features = {b},max_df = {c},min_df = {d},binary = {e})")
#                             x_test_input = x_test.toarray()
                            
#                             for j in list_imbalancer:                                                           # 3
#                                 if j != "Tanpa Imbalancer":
#                                     x_train_dense = x_train_awal.toarray().get()
#                                     y_train_cpu = y_train_awal.to_pandas() 

#                                     x_res, y_res = list_imbalancer[j].fit_resample(x_train_dense, y_train_cpu)
                                    
#                                     x_train_input = cp.array(x_res)
#                                     y_train_input = cudf.Series(y_res)

#                                 else :
#                                     x_train_input = x_train_awal.toarray()
#                                     y_train_input = y_train_awal

#                                 qiu_sekunder = []
#                                 for k in tuning_nb["alpha"] :
#                                     model = MultinomialNB(alpha= k)
#                                     model.fit(x_train_input, y_train_input)
#                                     y_pred = model.predict(x_test_input)
#                                     akurasi = accuracy_score(y_test, y_pred)
#                                     hq.heappush(qiu_sekunder,(-akurasi,counter,model,f"MultinomialNB(alpha = {k}), Akurasi = {akurasi}"))
#                                     counter += 1
                                
#                                 hasil = hq.heappop(qiu_sekunder)
#                                 model_nb = (hasil[2],hasil[3])
#                                 y_pred_train_nb = hasil[2].predict(x_train_input)
#                                 y_pred_test_nb = hasil[2].predict(x_test_input)
                                
#                                 qiu_sekunder = []
#                                 for k in tuning_svm["C"] :
#                                     for l in tuning_svm["loss"] :
#                                         for m in tuning_svm["max_iter"] :
#                                             for n in tuning_svm["fit_intercept"] :
#                                                 model = LinearSVC(C = k, loss = l, max_iter = m, fit_intercept = n)
#                                                 model.fit(x_train_input, y_train_input)
#                                                 y_pred = model.predict(x_test_input)
#                                                 akurasi = accuracy_score(y_test, y_pred)
#                                                 hq.heappush(qiu_sekunder,(-akurasi,counter,model,f"LinearSVC(C = {k}, loss = {l}, max_iter = {m}, fit_intercept = {n}), Akurasi = {akurasi}"))
#                                                 counter += 1
                                                
#                                 hasil = hq.heappop(qiu_sekunder)
#                                 model_svm = (hasil[2],hasil[3])
#                                 y_pred_train_svm = hasil[2].predict(x_train_input)
#                                 y_pred_test_svm = hasil[2].predict(x_test_input)
                                
#                                 qiu_sekunder = []
#                                 for k in tuning_rf["n_estimators"] :
#                                     for l in tuning_rf["max_depth"] :
#                                         for m in tuning_rf["min_samples_leaf"] :
#                                             for n in tuning_rf["n_bins"] :
#                                                 model = RandomForestClassifier(n_estimators = k, max_depth = l, min_samples_leaf = m, n_bins = n, random_state = 42)
#                                                 model.fit(x_train_input, y_train_input)
#                                                 y_pred = model.predict(x_test_input)
#                                                 akurasi = accuracy_score(y_test, y_pred)
#                                                 hq.heappush(qiu_sekunder,(-akurasi,counter,model,f"RandomForestClassifier(n_estimators = {k}, max_depth = {l}, min_samples_leaf = {m}, n_bins = {n}, random_state = 42), Akurasi = {akurasi}"))
#                                                 counter += 1
                                                
#                                 hasil = hq.heappop(qiu_sekunder)
#                                 model_rf = (hasil[2],hasil[3])
#                                 y_pred_train_rf = hasil[2].predict(x_train_input)
#                                 y_pred_test_rf = hasil[2].predict(x_test_input)
                                
#                                 x_train_meta = cudf.DataFrame({"pred_nb" : y_pred_train_nb, "pred_svm" : y_pred_train_svm, "pred_rf" : y_pred_train_rf})
#                                 x_test_meta = cudf.DataFrame({"pred_nb" : y_pred_test_nb, "pred_svm" : y_pred_test_svm, "pred_rf" : y_pred_test_rf})
                                
#                                 qiu_sekunder = []
#                                 for k in tuning_lr["C"] :
#                                     for l in tuning_lr["penalty"] :
#                                         for m in tuning_lr["max_iter"] :
#                                             for n in tuning_lr["linesearch_max_iter"] :
#                                                 model = LogisticRegression(C = k, penalty = l, max_iter = m, linesearch_max_iter = n)
#                                                 model.fit(x_train_meta, y_train_input)
#                                                 y_pred = model.predict(x_test_meta)
#                                                 akurasi = accuracy_score(y_test, y_pred)
#                                                 hq.heappush(qiu_sekunder,(-akurasi,counter,model,f"LogisticRegression(C = {k}, penalty = {l}, max_iter = {m}, linesearch_max_iter = {n}), Akurasi = {akurasi}"))
#                                                 counter += 1
                                                
#                                 hasil = hq.heappop(qiu_sekunder)
#                                 model_lr = (hasil[2],hasil[3])
#                                 hq.heappush(qiu_primer,(hasil[0],counter,kombinasi_stack(paket_data= h,tf_idf_model= tfidf, imbalancer= j, base_model_1= model_nb, base_model_2= model_svm, base_model_3= model_rf, meta_model= model_lr)))
#                                 counter += 1
#                                 z_counter += 1
#                                 print(f"{z_counter}/{total_gridsearch}")
#                                 del model_nb, model_svm, model_rf, model_lr
#                                 del x_train_meta, x_test_meta
#                                 gc.collect()
#                                 cp._default_memory_pool.free_all_blocks()

### Hasil

In [15]:
# import pickle

# list_top_20 = []

# for i in range(20) :
#     p = hq.heappop(qiu_primer)
#     list_top_20.append(p[2])
#     print(f"===== Juara {i+1} =====")
#     print(f"Paket Data   = {p[2].paket_data}")
#     print(f"tf_idf       = {p[2].tf_idf_model[1]}")
#     print(f"Imbalancer   = {p[2].imbalancer}")
#     print(f"Base Model 1 = {p[2].base_model_1[1]}")
#     print(f"Base Model 2 = {p[2].base_model_2[1]}")
#     print(f"Base Model 3 = {p[2].base_model_3[1]}")
#     print(f"Meta Model   = {p[2].meta_model[1]}")
    
#     if i == 0 :
#         nama_file = "Naive_Bayes_B1.pkl"
#         with open(nama_file, 'wb') as f:
#             pickle.dump(p[2].base_model_1[0], f)
#         nama_file = "Support_Vector_Machine_B2.pkl"
#         with open(nama_file, 'wb') as f:
#             pickle.dump(p[2].base_model_2[0], f)
#         nama_file = "Random_Forest_B3.pkl"
#         with open(nama_file, 'wb') as f:
#             pickle.dump(p[2].base_model_3[0], f)
#         nama_file = "Logistic_Linear_Meta.pkl"
#         with open(nama_file, 'wb') as f:
#             pickle.dump(p[2].meta_model[0], f)
#         nama_file = "Tf_Idf.pkl"
#         with open(nama_file, 'wb') as f:
#             pickle.dump(p[2].tf_idf_model[0], f)

## Grid Search Part 2

In [16]:
# data_5_batch = {"Imbalance" : data_5_val}#, "Balance" : data_5_val2}

# list_imbalancer = {
#     "Tanpa Imbalancer" : None
#     # ,"Smote" : SMOTE(random_state=42)
#     # ,"Random Under Sampler" : RandomUnderSampler(random_state=42)
# }

# tuning_tfidf = {"ngram_range": [(1,2)],"max_features": [10000],"max_df": [0.9],"min_df": [0.01], "binary": [False]}
# tuning_nb = {"alpha" : [1.0]}
# tuning_svm = {"C": [10], "loss" : ["hinge"], "max_iter" : [2000], "fit_intercept" : [True]}
# tuning_rf = {"n_estimators" : [200], "max_depth" : [16], "min_samples_leaf" : [3], "n_bins" : [15]}
# tuning_lr = {"C" : [0.01], "penalty" : ["l1"], "max_iter" : [100], "linesearch_max_iter" : [50]}

# qiu_primer = []
# counter = 0
# z_counter = 0
# total_gridsearch = len(data_5_batch) * 5 * len(list_imbalancer) * len(tuning_tfidf["ngram_range"]) * len(tuning_tfidf["max_features"]) * len(tuning_tfidf["max_df"]) * len(tuning_tfidf["min_df"]) * len(tuning_tfidf["binary"])
# for h in data_5_batch:                                                                                          # 2
#     paket_data = data_5_batch[h]
#     for i in range(len(paket_data)):                                                                            # 5
#         train = cudf.DataFrame({"clean_review" : [], "label_komen" : []})
#         test = cudf.DataFrame({"clean_review" : [], "label_komen" : []})
#         batch_data_test = i
        
#         for j in range(len(paket_data)):
#             if j == i:
#                 test = cudf.concat([test, paket_data[j]], axis=0, ignore_index=True)
#             else:
#                 train = cudf.concat([train, paket_data[j]], axis=0, ignore_index=True)
        
#         train['clean_review'] = train['clean_review'].fillna('')
#         test['clean_review'] = test['clean_review'].fillna('')
        
#         for a in tuning_tfidf["ngram_range"] :                                                                  # 3
#             for b in tuning_tfidf["max_features"] :
#                 for c in tuning_tfidf["max_df"] :
#                     for d in tuning_tfidf["min_df"] :
#                         for e in tuning_tfidf["binary"] :
                            
#                             tfidf_vectorizer = TfidfVectorizer(ngram_range= a,max_features= b,max_df= c,min_df= d,binary= e)
#                             x_train_awal = tfidf_vectorizer.fit_transform(train['clean_review'])
#                             x_test = tfidf_vectorizer.transform(test["clean_review"])
                            
#                             y_train_awal = train["label_komen"]
#                             y_test = test["label_komen"]
                            
#                             tfidf = (tfidf_vectorizer, f"TfidfVectorizer(ngram_range = {a},max_features = {b},max_df = {c},min_df = {d},binary = {e})")
#                             x_test_input = x_test.toarray()
                            
#                             for j in list_imbalancer:                                                           # 3
#                                 if j != "Tanpa Imbalancer":
#                                     x_train_dense = x_train_awal.toarray().get()
#                                     y_train_cpu = y_train_awal.to_pandas() 

#                                     x_res, y_res = list_imbalancer[j].fit_resample(x_train_dense, y_train_cpu)
                                    
#                                     x_train_input = cp.array(x_res)
#                                     y_train_input = cudf.Series(y_res)

#                                 else :
#                                     x_train_input = x_train_awal.toarray()
#                                     y_train_input = y_train_awal

#                                 best_akurasi = 0
#                                 for k in tuning_nb["alpha"] :
#                                     model = MultinomialNB(alpha= k)
#                                     model.fit(x_train_input, y_train_input)
#                                     y_pred = model.predict(x_test_input)
#                                     akurasi = accuracy_score(y_test, y_pred)
#                                     if akurasi > best_akurasi:
#                                         best_akurasi = akurasi
#                                         model_nb = (model,f"MultinomialNB(alpha = {k}), Akurasi = {akurasi}")
#                                     else:
#                                         del model
#                                         cp._default_memory_pool.free_all_blocks()
#                                 y_pred_train_nb = model_nb[0].predict(x_train_input)
#                                 y_pred_test_nb = model_nb[0].predict(x_test_input)
                                
#                                 best_akurasi = 0
#                                 for k in tuning_svm["C"] :
#                                     for l in tuning_svm["loss"] :
#                                         for m in tuning_svm["max_iter"] :
#                                             for n in tuning_svm["fit_intercept"] :
#                                                 model = LinearSVC(C = k, loss = l, max_iter = m, fit_intercept = n)
#                                                 model.fit(x_train_input, y_train_input)
#                                                 y_pred = model.predict(x_test_input)
#                                                 akurasi = accuracy_score(y_test, y_pred)
#                                                 if akurasi > best_akurasi:
#                                                     best_akurasi = akurasi
#                                                     model_svm = (model,f"LinearSVC(C = {k}, loss = {l}, max_iter = {m}, fit_intercept = {n}), Akurasi = {akurasi}")
#                                                 else:
#                                                     del model
#                                                     cp._default_memory_pool.free_all_blocks()
#                                 y_pred_train_svm = model_svm[0].predict(x_train_input)
#                                 y_pred_test_svm = model_svm[0].predict(x_test_input)
                                
#                                 best_akurasi = 0
#                                 for k in tuning_rf["n_estimators"] :
#                                     for l in tuning_rf["max_depth"] :
#                                         for m in tuning_rf["min_samples_leaf"] :
#                                             for n in tuning_rf["n_bins"] :
#                                                 model = RandomForestClassifier(n_estimators = k, max_depth = l, min_samples_leaf = m, n_bins = n, random_state = 42)
#                                                 model.fit(x_train_input, y_train_input)
#                                                 y_pred = model.predict(x_test_input)
#                                                 akurasi = accuracy_score(y_test, y_pred)
#                                                 if akurasi > best_akurasi:
#                                                     best_akurasi = akurasi
#                                                     model_rf = (model,f"RandomForestClassifier(n_estimators = {k}, max_depth = {l}, min_samples_leaf = {m}, n_bins = {n}, random_state = 42), Akurasi = {akurasi}")
#                                                 else:
#                                                     del model
#                                                     cp._default_memory_pool.free_all_blocks()
#                                 y_pred_train_rf = model_rf[0].predict(x_train_input)
#                                 y_pred_test_rf = model_rf[0].predict(x_test_input)
                                
#                                 x_train_meta = cudf.DataFrame({"pred_nb" : y_pred_train_nb, "pred_svm" : y_pred_train_svm, "pred_rf" : y_pred_train_rf})
#                                 x_test_meta = cudf.DataFrame({"pred_nb" : y_pred_test_nb, "pred_svm" : y_pred_test_svm, "pred_rf" : y_pred_test_rf})
                                
#                                 best_akurasi = 0
#                                 for k in tuning_lr["C"] :
#                                     for l in tuning_lr["penalty"] :
#                                         for m in tuning_lr["max_iter"] :
#                                             for n in tuning_lr["linesearch_max_iter"] :
#                                                 model = LogisticRegression(C = k, penalty = l, max_iter = m, linesearch_max_iter = n)
#                                                 model.fit(x_train_meta, y_train_input)
#                                                 y_pred = model.predict(x_test_meta)
#                                                 akurasi = accuracy_score(y_test, y_pred)
#                                                 if akurasi > best_akurasi:
#                                                     best_akurasi = akurasi
#                                                     model_lr = (model,f"LogisticRegression(C = {k}, penalty = {l}, max_iter = {m}, linesearch_max_iter = {n}), Akurasi = {akurasi}")
#                                                 else:
#                                                     del model
#                                                     cp._default_memory_pool.free_all_blocks()
#                                 hq.heappush(qiu_primer,(-best_akurasi,counter,kombinasi_stack(paket_data= h,tf_idf_model= tfidf, imbalancer= j, base_model_1= model_nb, base_model_2= model_svm, base_model_3= model_rf, meta_model= model_lr),i))
#                                 counter += 1
#                                 z_counter += 1
#                                 print(f"{z_counter}/{total_gridsearch}")
#                                 del model_nb, model_svm, model_rf, model_lr
#                                 del x_train_meta, x_test_meta
#                                 gc.collect()
#                                 cp._default_memory_pool.free_all_blocks()

In [17]:
data_5_batch = {"Balance" : data_5_val2}

list_imbalancer = {
    "Tanpa Imbalancer" : None
    # ,"Smote" : SMOTE(random_state=42)
    # ,"Random Under Sampler" : RandomUnderSampler(random_state=42)
}

tuning_tfidf = {"ngram_range": [(1,1),(1,2)],"max_features": [10000],"max_df": [0.9],"min_df": [0.01], "binary": [False]}
tuning_nb = {"alpha" : [0.1,1.0,10]}
tuning_svm = {"C": [1,10], "loss" : ["hinge"], "max_iter" : [2000], "fit_intercept" : [True]}
tuning_rf = {"n_estimators" : [200], "max_depth" : [16], "min_samples_leaf" : [3,5], "n_bins" : [15,32,64]}
tuning_lr = {"C" : [0.01,0.1], "penalty" : ["l1"], "max_iter" : [100], "linesearch_max_iter" : [50]}

qiu_primer = []
counter = 0
z_counter = 0
total_gridsearch = len(data_5_batch) * 5 * len(list_imbalancer) * len(tuning_tfidf["ngram_range"]) * len(tuning_tfidf["max_features"]) * len(tuning_tfidf["max_df"]) * len(tuning_tfidf["min_df"]) * len(tuning_tfidf["binary"]) * len(tuning_nb["alpha"]) * len(tuning_svm["C"]) * len(tuning_svm["loss"]) * len(tuning_svm["max_iter"]) * len(tuning_svm["fit_intercept"]) * len(tuning_rf["n_estimators"]) * len(tuning_rf["max_depth"]) * len(tuning_rf["min_samples_leaf"]) * len(tuning_rf["n_bins"]) * len(tuning_lr["C"])  * len(tuning_lr["penalty"]) * len(tuning_lr["max_iter"]) * len(tuning_lr["linesearch_max_iter"])
for h in data_5_batch:                                                                                          # 2
    paket_data = data_5_batch[h]
    for i in range(len(paket_data)):                                                                            # 5
        train = cudf.DataFrame({"clean_review" : [], "label_komen" : []})
        test = cudf.DataFrame({"clean_review" : [], "label_komen" : []})
        batch_data_test = i
        
        for j in range(len(paket_data)):
            if j == i:
                test = cudf.concat([test, paket_data[j]], axis=0, ignore_index=True)
            else:
                train = cudf.concat([train, paket_data[j]], axis=0, ignore_index=True)
        
        train['clean_review'] = train['clean_review'].fillna('')
        test['clean_review'] = test['clean_review'].fillna('')
        
        for a in tuning_tfidf["ngram_range"] :                                                                  # 3
            for b in tuning_tfidf["max_features"] :
                for c in tuning_tfidf["max_df"] :
                    for d in tuning_tfidf["min_df"] :
                        for e in tuning_tfidf["binary"] :
                            
                            tfidf_vectorizer = TfidfVectorizer(ngram_range= a,max_features= b,max_df= c,min_df= d,binary= e)
                            x_train_awal = tfidf_vectorizer.fit_transform(train['clean_review'])
                            x_test = tfidf_vectorizer.transform(test["clean_review"])
                            
                            y_train_awal = train["label_komen"]
                            y_test = test["label_komen"]
                            
                            tfidf = (tfidf_vectorizer, f"TfidfVectorizer(ngram_range = {a},max_features = {b},max_df = {c},min_df = {d},binary = {e})")
                            x_test_input = x_test.toarray()
                            
                            for j in list_imbalancer:                                                           # 3
                                if j != "Tanpa Imbalancer":
                                    x_train_dense = x_train_awal.toarray().get()
                                    y_train_cpu = y_train_awal.to_pandas() 

                                    x_res, y_res = list_imbalancer[j].fit_resample(x_train_dense, y_train_cpu)
                                    
                                    x_train_input = cp.array(x_res)
                                    y_train_input = cudf.Series(y_res)

                                else :
                                    x_train_input = x_train_awal.toarray()
                                    y_train_input = y_train_awal
                                for k in tuning_nb["alpha"] :
                                    model = MultinomialNB(alpha= k)
                                    model.fit(x_train_input, y_train_input)
                                    y_pred = model.predict(x_test_input)
                                    akurasi = accuracy_score(y_test, y_pred)
                                    model_nb = (model,f"MultinomialNB(alpha = {k}), Akurasi = {akurasi}")
                                    y_pred_train_nb = model_nb[0].predict(x_train_input)
                                    y_pred_test_nb = model_nb[0].predict(x_test_input)
                                    
                                    for k in tuning_svm["C"] :
                                        for l in tuning_svm["loss"] :
                                            for m in tuning_svm["max_iter"] :
                                                for n in tuning_svm["fit_intercept"] :
                                                    model = LinearSVC(C = k, loss = l, max_iter = m, fit_intercept = n)
                                                    model.fit(x_train_input, y_train_input)
                                                    y_pred = model.predict(x_test_input)
                                                    akurasi = accuracy_score(y_test, y_pred)
                                                    model_svm = (model,f"LinearSVC(C = {k}, loss = {l}, max_iter = {m}, fit_intercept = {n}), Akurasi = {akurasi}")
                                                    y_pred_train_svm = model_svm[0].predict(x_train_input)
                                                    y_pred_test_svm = model_svm[0].predict(x_test_input)
                                                    
                                                    for o in tuning_rf["n_estimators"] :
                                                        for p in tuning_rf["max_depth"] :
                                                            for q in tuning_rf["min_samples_leaf"] :
                                                                for r in tuning_rf["n_bins"] :
                                                                    model = RandomForestClassifier(n_estimators = o, max_depth = p, min_samples_leaf = q, n_bins = r, random_state = 42)
                                                                    model.fit(x_train_input, y_train_input)
                                                                    y_pred = model.predict(x_test_input)
                                                                    akurasi = accuracy_score(y_test, y_pred)
                                                                    model_rf = (model,f"RandomForestClassifier(n_estimators = {o}, max_depth = {p}, min_samples_leaf = {q}, n_bins = {r}, random_state = 42), Akurasi = {akurasi}")
                                                                    y_pred_train_rf = model_rf[0].predict(x_train_input)
                                                                    y_pred_test_rf = model_rf[0].predict(x_test_input)
                                
                                                                    x_train_meta = cudf.DataFrame({"pred_nb" : y_pred_train_nb, "pred_svm" : y_pred_train_svm, "pred_rf" : y_pred_train_rf})
                                                                    x_test_meta = cudf.DataFrame({"pred_nb" : y_pred_test_nb, "pred_svm" : y_pred_test_svm, "pred_rf" : y_pred_test_rf})
                                
                                                                    for s in tuning_lr["C"] :
                                                                        for t in tuning_lr["penalty"] :
                                                                            for u in tuning_lr["max_iter"] :
                                                                                for v in tuning_lr["linesearch_max_iter"] :
                                                                                    model = LogisticRegression(C = s, penalty = t, max_iter = u, linesearch_max_iter = v)
                                                                                    model.fit(x_train_meta, y_train_input)
                                                                                    y_pred = model.predict(x_test_meta)
                                                                                    akurasi = accuracy_score(y_test, y_pred)
                                                                                    model_lr = (model,f"LogisticRegression(C = {s} penalty = {t}, max_iter = {u}, linesearch_max_iter = {v}), Akurasi = {akurasi}")
                                                                                    hq.heappush(qiu_primer,(-akurasi,counter,kombinasi_stack(paket_data= h,tf_idf_model= tfidf, imbalancer= j, base_model_1= model_nb, base_model_2= model_svm, base_model_3= model_rf, meta_model= model_lr),i))
                                                                                    counter += 1
                                                                                    z_counter += 1
                                                                                    print(f"{z_counter}/{total_gridsearch}")
                                                                                    gc.collect()
                                                                                    cp._default_memory_pool.free_all_blocks()

1/720
2/720
[2026-06-24 07:46:33.167] [CUML] [warning] QWL-QN line search failed (code 3); stopping at the last valid step
3/720
4/720
5/720
6/720
[2026-06-24 07:46:46.722] [CUML] [warning] QWL-QN line search failed (code 3); stopping at the last valid step
7/720
8/720
9/720
10/720
[2026-06-24 07:47:00.288] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
11/720
12/720
13/720
14/720
15/720
16/720
17/720
18/720
[2026-06-24 07:47:29.647] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
19/720
20/720
[2026-06-24 07:47:36.594] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
21/720
[2026-06-24 07:47:36.827] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
22/720
23/720
24/720
25/720
26/720
27/720
28/720
29/720
30/720
31/720
32/720
33/720
34/720
[2026-06-24 07:48:28.777] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
35/720
36/720
[2026-06-24 07:48:31.160] [CUML] [warning] L-BFGS stopped, because the line search failed to advance (step delta = 0.000000)
[2026-06-24 07:48:37.991] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
37/720
38/720
[2026-06-24 07:48:45.224] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
39/720
40/720
41/720
[2026-06-24 07:48:52.697] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
42/720
[2026-06-24 07:48:59.624] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
43/720
[2026-06-24 07:48:59.870] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
44/720
[2026-06-24 07:49:06.783] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
45/720
[2026-06-24 07:49:07.041] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
46/720
[2026-06-24 07:49:13.935] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
47/720
48/720
49/720
[2026-06-24 07:49:23.562] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
50/720
51/720
[2026-06-24 07:49:30.809] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
52/720
[2026-06-24 07:49:37.863] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
53/720
54/720
[2026-06-24 07:49:45.077] [CUML] [warning] QWL-QN line search failed (code 3); stopping at the last valid step
55/720
56/720
[2026-06-24 07:49:52.410] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
57/720
58/720
59/720
60/720
61/720
62/720
63/720
64/720
65/720
66/720
67/720
68/720
[2026-06-24 07:50:39.011] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
69/720
70/720
71/720
72/720
73/720
74/720
75/720
[2026-06-24 07:51:09.734] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
76/720
77/720
78/720
79/720
[2026-06-24 07:51:24.691] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
80/720
81/720
82/720
83/720
84/720
[2026-06-24 07:51:48.807] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
85/720
86/720
87/720
88/720
89/720
[2026-06-24 07:52:04.063] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
90/720
91/720
92/720
93/720
94/720
95/720
96/720
97/720
98/720
99/720
100/720
101/720
102/720
[2026-06-24 07:52:58.113] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
103/720
104/720
105/720
[2026-06-24 07:53:05.732] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
106/720
107/720
[2026-06-24 07:53:13.091] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
108/720
109/720
110/720
111/720
112/720
113/720
114/720
115/720
116/720
117/720
118/720
119/720
120/720
[2026-06-24 07:54:10.036] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
121/720
122/720
[2026-06-24 07:54:17.560] [CUML] [warning] QWL-QN line search failed (code 3); stopping at the last valid step
123/720
124/720
125/720
[2026-06-24 07:54:25.280] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
126/720
127/720
128/720
129/720
[2026-06-24 07:54:40.264] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
130/720
131/720
[2026-06-24 07:54:47.671] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
132/720
[2026-06-24 07:54:57.617] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
133/720
134/720
[2026-06-24 07:55:05.150] [CUML] [warning] QWL-QN line search failed (code 3); stopping at the last valid step
135/720
136/720
137/720
138/720
139/720
[2026-06-24 07:55:20.278] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
140/720
141/720
142/720
143/720
144/720
145/720
146/720
[2026-06-24 07:55:54.026] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
147/720
[2026-06-24 07:55:54.258] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
148/720
149/720
150/720
151/720
152/720
[2026-06-24 07:56:16.121] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
153/720
[2026-06-24 07:56:16.354] [CUML] [warning] QWL-QN line search failed (code 3); stopping at the last valid step
154/720
[2026-06-24 07:56:23.436] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
155/720
156/720
157/720
[2026-06-24 07:56:33.114] [CUML] [warning] QWL-QN line search failed (code 3); stopping at the last valid step
158/720
159/720
160/720
161/720
162/720
[2026-06-24 07:56:55.167] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
163/720
164/720
[2026-06-24 07:57:02.463] [CUML] [warning] QWL-QN line search failed (code 3); stopping at the last valid step
165/720
166/720
167/720
168/720
[2026-06-24 07:57:19.238] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
169/720
170/720
171/720
[2026-06-24 07:57:26.924] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
172/720
173/720
[2026-06-24 07:57:34.350] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
174/720
175/720
176/720
177/720
178/720
[2026-06-24 07:57:56.099] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
179/720
180/720
181/720
182/720
[2026-06-24 07:58:12.893] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
183/720
184/720
[2026-06-24 07:58:20.331] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
185/720
[2026-06-24 07:58:20.566] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
186/720
187/720
[2026-06-24 07:58:27.956] [CUML] [warning] QWL-QN line search failed (code 3); stopping at the last valid step
188/720
189/720
190/720
191/720
192/720
193/720
194/720
195/720
196/720
197/720
198/720
199/720
200/720
201/720
202/720
203/720
204/720
205/720
206/720
207/720
208/720
209/720
210/720
211/720
212/720
[2026-06-24 08:00:07.816] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
213/720
[2026-06-24 08:00:08.071] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
214/720
215/720
[2026-06-24 08:00:15.444] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
216/720
[2026-06-24 08:00:30.452] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
217/720
218/720
219/720
220/720
[2026-06-24 08:00:45.602] [CUML] [warning] QWL-QN line search failed (code 3); stopping at the last valid step
221/720
222/720
[2026-06-24 08:00:53.113] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
223/720
224/720
225/720
226/720
227/720
228/720
[2026-06-24 08:01:17.708] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
229/720
230/720
231/720
232/720
233/720
[2026-06-24 08:01:33.048] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
234/720
235/720
[2026-06-24 08:01:40.572] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
236/720
237/720
[2026-06-24 08:01:48.034] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
238/720
239/720
240/720
241/720
242/720
243/720
244/720
245/720
246/720
[2026-06-24 08:02:28.330] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
247/720
248/720
249/720
250/720
[2026-06-24 08:02:43.191] [CUML] [warning] QWL-QN line search failed (code 3); stopping at the last valid step
251/720
[2026-06-24 08:02:43.420] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
252/720
253/720
254/720
255/720
256/720
[2026-06-24 08:03:07.716] [CUML] [warning] QWL-QN line search failed (code 3); stopping at the last valid step
257/720
258/720
[2026-06-24 08:03:15.192] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
259/720
260/720
261/720
262/720
[2026-06-24 08:03:30.090] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
263/720
264/720
265/720
266/720
267/720
268/720
269/720
[2026-06-24 08:03:55.526] [CUML] [warning] QWL-QN line search failed (code 3); stopping at the last valid step
270/720
[2026-06-24 08:04:02.817] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
271/720
272/720
[2026-06-24 08:04:10.238] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
273/720
274/720
275/720
276/720
277/720
[2026-06-24 08:04:27.395] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
278/720
279/720
[2026-06-24 08:04:34.951] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
280/720
281/720
282/720
283/720
284/720
285/720
286/720
287/720
288/720
[2026-06-24 08:05:16.840] [CUML] [warning] QWL-QN line search failed (code 3); stopping at the last valid step
289/720
[2026-06-24 08:05:17.099] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
290/720
[2026-06-24 08:05:24.442] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
291/720
292/720
293/720
294/720
295/720
296/720
297/720
298/720
299/720
300/720
301/720
302/720
303/720
304/720
305/720
306/720
[2026-06-24 08:06:27.021] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
307/720
308/720
309/720
[2026-06-24 08:06:34.699] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
310/720
311/720
312/720
313/720
[2026-06-24 08:06:52.859] [CUML] [warning] QWL-QN line search failed (code 3); stopping at the last valid step
314/720
315/720
316/720
317/720
318/720
319/720
320/720
321/720
322/720
323/720
324/720
[2026-06-24 08:07:39.685] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
325/720
[2026-06-24 08:07:39.917] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
326/720
327/720
328/720
[2026-06-24 08:07:54.883] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
329/720
330/720
331/720
[2026-06-24 08:08:02.689] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
332/720
333/720
[2026-06-24 08:08:10.149] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
334/720
335/720
336/720
337/720
338/720
[2026-06-24 08:08:35.065] [CUML] [warning] QWL-QN line search failed (code 3); stopping at the last valid step
339/720
340/720
[2026-06-24 08:08:42.654] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
341/720
342/720
[2026-06-24 08:08:50.188] [CUML] [warning] QWL-QN line search failed (code 3); stopping at the last valid step
343/720
344/720
345/720
346/720
[2026-06-24 08:09:05.117] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
347/720
[2026-06-24 08:09:05.338] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
348/720
[2026-06-24 08:09:15.253] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
349/720
[2026-06-24 08:09:15.473] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
350/720
351/720
352/720
353/720
354/720
[2026-06-24 08:09:37.981] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
355/720
356/720
357/720
[2026-06-24 08:09:45.700] [CUML] [warning] QWL-QN line search failed (code 3); stopping at the last valid step
358/720
[2026-06-24 08:09:52.937] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
359/720
360/720
361/720
362/720
363/720
[2026-06-24 08:10:16.997] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
364/720
365/720
[2026-06-24 08:10:24.675] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
366/720
367/720
368/720
369/720
370/720
371/720
372/720
[2026-06-24 08:10:56.789] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
373/720
[2026-06-24 08:10:57.015] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
374/720
375/720
376/720
377/720
378/720
[2026-06-24 08:11:19.800] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
379/720
380/720
[2026-06-24 08:11:27.347] [CUML] [warning] QWL-QN line search failed (code 3); stopping at the last valid step
381/720
382/720
383/720
384/720
[2026-06-24 08:11:44.974] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
385/720
[2026-06-24 08:11:45.220] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
386/720
387/720
388/720
389/720
390/720
[2026-06-24 08:12:07.967] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
391/720
[2026-06-24 08:12:08.192] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
392/720
[2026-06-24 08:12:15.550] [CUML] [warning] QWL-QN line search failed (code 3); stopping at the last valid step
393/720
394/720
395/720
396/720
397/720
398/720
399/720
[2026-06-24 08:12:40.977] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
400/720
401/720
402/720
403/720
404/720
405/720
[2026-06-24 08:13:03.854] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
406/720
[2026-06-24 08:13:11.221] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
407/720
[2026-06-24 08:13:11.452] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
408/720
409/720
410/720
411/720
412/720
413/720
414/720
415/720
[2026-06-24 08:13:44.967] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
416/720
417/720
[2026-06-24 08:13:52.557] [CUML] [warning] QWL-QN line search failed (code 3); stopping at the last valid step
418/720
[2026-06-24 08:13:59.903] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
419/720
420/720
[2026-06-24 08:14:09.745] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
421/720
422/720
423/720
424/720
425/720
426/720
427/720
428/720
[2026-06-24 08:14:40.253] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
429/720
430/720
431/720
432/720
433/720
434/720
[2026-06-24 08:15:07.480] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
435/720
436/720
437/720
438/720
[2026-06-24 08:15:22.609] [CUML] [warning] QWL-QN line search failed (code 3); stopping at the last valid step
439/720
440/720
441/720
442/720
443/720
444/720
445/720
446/720
[2026-06-24 08:15:54.787] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
447/720
[2026-06-24 08:15:55.025] [CUML] [warning] QWL-QN line search failed (code 3); stopping at the last valid step
448/720
449/720
[2026-06-24 08:16:02.595] [CUML] [warning] QWL-QN line search failed (code 3); stopping at the last valid step
450/720
[2026-06-24 08:16:09.886] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
451/720
452/720
453/720
454/720
[2026-06-24 08:16:24.822] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
455/720
456/720
[2026-06-24 08:16:34.826] [CUML] [warning] QWL-QN line search failed (code 3); stopping at the last valid step
457/720
[2026-06-24 08:16:35.057] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
458/720
459/720
460/720
461/720
462/720
463/720
464/720
465/720
466/720
[2026-06-24 08:17:12.616] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
467/720
[2026-06-24 08:17:12.849] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
468/720
469/720
470/720
471/720
[2026-06-24 08:17:29.814] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
472/720
473/720
474/720
475/720
476/720
477/720
478/720
479/720
480/720
[2026-06-24 08:18:09.389] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
481/720
482/720
483/720
484/720
485/720
486/720
[2026-06-24 08:18:32.139] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
487/720
488/720
489/720
490/720
[2026-06-24 08:18:47.046] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
491/720
[2026-06-24 08:18:47.305] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)
492/720
493/720
494/720
[2026-06-24 08:19:03.957] [CUML] [warning] QWL-QN stopped, because the line search failed to advance (step delta = 0.000000)

In [18]:
list_top_20_p2 = []

for i in range(total_gridsearch) :
    p = hq.heappop(qiu_primer)
    list_top_20_p2.append(p[2])
    print(f"===== Juara {i+1} =====")
    print(f"Paket Data   = {p[2].paket_data}")
    print(f"tf_idf       = {p[2].tf_idf_model[1]}")
    print(f"Imbalancer   = {p[2].imbalancer}")
    print(f"Base Model 1 = {p[2].base_model_1[1]}")
    print(f"Base Model 2 = {p[2].base_model_2[1]}")
    print(f"Base Model 3 = {p[2].base_model_3[1]}")
    print(f"Meta Model   = {p[2].meta_model[1]}")
    print(f"Batch Test   = {p[3]}")

===== Juara 1 =====
Paket Data   = Balance
tf_idf       = TfidfVectorizer(ngram_range = (1, 2),max_features = 10000,max_df = 0.9,min_df = 0.01,binary = False)
Imbalancer   = Tanpa Imbalancer
Base Model 1 = MultinomialNB(alpha = 1.0), Akurasi = 0.7907094851957813
Base Model 2 = LinearSVC(C = 10, loss = hinge, max_iter = 2000, fit_intercept = True), Akurasi = 0.8244993313131656
Base Model 3 = RandomForestClassifier(n_estimators = 200, max_depth = 16, min_samples_leaf = 3, n_bins = 15, random_state = 42), Akurasi = 0.73132332278106
Meta Model   = LogisticRegression(C = 0.01 penalty = l1, max_iter = 100, linesearch_max_iter = 50), Akurasi = 0.8244485449713057
Batch Test   = 2
===== Juara 2 =====
Paket Data   = Balance
tf_idf       = TfidfVectorizer(ngram_range = (1, 2),max_features = 10000,max_df = 0.9,min_df = 0.01,binary = False)
Imbalancer   = Tanpa Imbalancer
Base Model 1 = MultinomialNB(alpha = 1.0), Akurasi = 0.7907094851957813
Base Model 2 = LinearSVC(C = 10, loss = hinge, max_iter = 2000, fit_intercept = True), Akurasi = 0.8244993313131656
Base Model 3 = RandomForestClassifier(n_estimators = 200, max_depth = 16, min_samples_leaf = 3, n_bins = 15, random_state = 42), Akurasi = 0.73132332278106
Meta Model   = LogisticRegression(C = 0.1 penalty = l1, max_iter = 100, linesearch_max_iter = 50), Akurasi = 0.8244485449713057
Batch Test   = 2
===== Juara 3 =====
Paket Data   = Balance
tf_idf       = TfidfVectorizer(ngram_range = (1, 2),max_features = 10000,max_df = 0.9,min_df = 0.01,binary = False)
Imbalancer   = Tanpa Imbalancer
Base Model 1 = MultinomialNB(alpha = 1.0), Akurasi = 0.7907094851957813
Base Model 2 = LinearSVC(C = 10, loss = hinge, max_iter = 2000, fit_intercept = True), Akurasi = 0.8244993313131656
Base Model 3 = RandomForestClassifier(n_estimators = 200, max_depth = 16, min_samples_leaf = 5, n_bins = 32, random_state = 42), Akurasi = 0.7292918691066682
Meta Model   = LogisticRegression(C = 0.01 penalty = l1, max_iter = 100, linesearch_max_iter = 50), Akurasi = 0.8244485449713057
Batch Test   = 2
===== Juara 4 =====
Paket Data   = Balance
tf_idf       = TfidfVectorizer(ngram_range = (1, 2),max_features = 10000,max_df = 0.9,min_df = 0.01,binary = False)
Imbalancer   = Tanpa Imbalancer
Base Model 1 = MultinomialNB(alpha = 1.0), Akurasi = 0.7907094851957813
Base Model 2 = LinearSVC(C = 10, loss = hinge, max_iter = 2000, fit_intercept = True), Akurasi = 0.8244993313131656
Base Model 3 = RandomForestClassifier(n_estimators = 200, max_depth = 16, min_samples_leaf = 5, n_bins = 32, random_state = 42), Akurasi = 0.7292918691066682
Meta Model   = LogisticRegression(C = 0.1 penalty = l1, max_iter = 100, linesearch_max_iter = 50), Akurasi = 0.8244485449713057
Batch Test   = 2
===== Juara 5 =====
Paket Data   = Balance
tf_idf       = TfidfVectorizer(ngram_range = (1, 2),max_features = 10000,max_df = 0.9,min_df = 0.01,binary = False)
Imbalancer   = Tanpa Imbalancer
Base Model 1 = MultinomialNB(alpha = 1.0), Akurasi = 0.7907094851957813
Base Model 2 = LinearSVC(C = 10, loss = hinge, max_iter = 2000, fit_intercept = True), Akurasi = 0.8244993313131656
Base Model 3 = RandomForestClassifier(n_estimators = 200, max_depth = 16, min_samples_leaf = 5, n_bins = 64, random_state = 42), Akurasi = 0.730341453505104
Meta Model   = LogisticRegression(C = 0.01 penalty = l1, max_iter = 100, linesearch_max_iter = 50), Akurasi = 0.8244485449713057
Batch Test   = 2
===== Juara 6 =====
Paket Data   = Balance
tf_idf       = TfidfVectorizer(ngram_range = (1, 2),max_features = 10000,max_df = 0.9,min_df = 0.01,binary = False)
Imbalancer   = Tanpa Imbalancer
Base Model 1 = MultinomialNB(alpha = 1.0), Akurasi = 0.7907094851957813
Base Model 2 = LinearSVC(C = 10, loss = hinge, max_iter = 2000, fit_intercept = True), Akurasi = 0.8244993313131656
Base Model 3 = RandomForestClassifier(n_estimators = 200, max_depth = 16, min_samples_leaf = 5, n_bins = 64, random_state = 42), Akurasi = 0.730341453505104
Meta Model   = LogisticRegression(C = 0.1 penalty = l1, max_iter = 100, linesearch_max_iter = 50), Akurasi = 0.8244485449713057
Batch Test   = 2
===== Juara 7 =====
Paket Data   = Balance
tf_idf       = TfidfVectorizer(ngram_range = (1, 2),max_features = 10000,max_df = 0.9,min_df = 0.01,binary = False)
Imbalancer   = Tanpa Imbalancer
Base Model 1 = MultinomialNB(alpha = 1.0), Akurasi = 0.7907094851957813
Base Model 2 = LinearSVC(C = 10, loss = hinge, max_iter = 2000, fit_intercept = True), Akurasi = 0.8244993313131656
Base Model 3 = RandomForestClassifier(n_estimators = 200, max_depth = 16, min_samples_leaf = 3, n_bins = 32, random_state = 42), Akurasi = 0.7290210086167493
Meta Model   = LogisticRegression(C = 0.01 penalty = l1, max_iter = 100, linesearch_max_iter = 50), Akurasi = 0.8244146874100658
Batch Test   = 2
===== Juara 8 =====
Paket Data   = Balance
tf_idf       = TfidfVectorizer(ngram_range = (1, 2),max_features = 10000,max_df = 0.9,min_df = 0.01,binary = False)
Imbalancer   = Tanpa Imbalancer
Base Model 1 = MultinomialNB(alpha = 1.0), Akurasi = 0.7907094851957813
Base Model 2 = LinearSVC(C = 10, loss = hinge, max_iter = 2000, fit_intercept = True), Akurasi = 0.8244993313131656
Base Model 3 = RandomForestClassifier(n_estimators = 200, max_depth = 16, min_samples_leaf = 3, n_bins = 32, random_state = 42), Akurasi = 0.7290210086167493
Meta Model   = LogisticRegression(C = 0.1 penalty = l1, max_iter = 100, linesearch_max_iter = 50), Akurasi = 0.8244146874100658
Batch Test   = 2
===== Juara 9 =====
Paket Data   = Balance
tf_idf       = TfidfVectorizer(ngram_range = (1, 2),max_features = 10000,max_df = 0.9,min_df = 0.01,binary = False)
Imbalancer   = Tanpa Imbalancer
Base Model 1 = MultinomialNB(alpha = 1.0), Akurasi = 0.7907094851957813
Base Model 2 = LinearSVC(C = 10, loss = hinge, max_iter = 2000, fit_intercept = True), Akurasi = 0.8244993313131656
Base Model 3 = RandomForestClassifier(n_estimators = 200, max_depth = 16, min_samples_leaf = 3, n_bins = 64, random_state = 42), Akurasi = 0.7287670769074504
Meta Model   = LogisticRegression(C = 0.01 penalty = l1, max_iter = 100, linesearch_max_iter = 50), Akurasi = 0.8244146874100658
Batch Test   = 2
===== Juara 10 =====
Paket Data   = Balance
tf_idf       = TfidfVectorizer(ngram_range = (1, 2),max_features = 10000,max_df = 0.9,min_df = 0.01,binary = False)
Imbalancer   = Tanpa Imbalancer
Base Model 1 = MultinomialNB(alpha = 1.0), Akurasi = 0.7907094851957813
Base Model 2 = LinearSVC(C = 10, loss = hinge, max_iter = 2000, fit_intercept = True), Akurasi = 0.8244993313131656
Base Model 3 = RandomForestClassifier(n_estimators = 200, max_depth = 16, min_samples_leaf = 3, n_bins = 64, random_state = 42), Akurasi = 0.7287670769074504
Meta Model   = LogisticRegression(C = 0.1 penalty = l1, max_iter = 100, linesearch_max_iter = 50), Akurasi = 0.8244146874100658
Batch Test   = 2
===== Juara 11 =====
Paket Data   = Balance
tf_idf       = TfidfVectorizer(ngram_range = (1, 2),max_features = 10000,max_df = 0.9,min_df = 0.01,binary = False)
Imbalancer   = Tanpa Imbalancer
Base Model 1 = MultinomialNB(alpha = 1.0), Akurasi = 0.7907094851957813
Base Model 2 = LinearSVC(C = 10, loss = hinge, max_iter = 2000, fit_intercept = True), Akurasi = 0.8244993313131656
Base Model 3 = RandomForestClassifier(n_estimators = 200, max_depth = 16, min_samples_leaf = 5, n_bins = 15, random_state = 42), Akurasi = 0.730341453505104
Meta Model   = LogisticRegression(C = 0.01 penalty = l1, max_iter = 100, linesearch_max_iter = 50), Akurasi = 0.8244146874100658
Batch Test   = 2
===== Juara 12 =====
Paket Data   = Balance
tf_idf       = TfidfVectorizer(ngram_range = (1, 2),max_features = 10000,max_df = 0.9,min_df = 0.01,binary = False)
Imbalancer   = Tanpa Imbalancer
Base Model 1 = MultinomialNB(alpha = 1.0), Akurasi = 0.7907094851957813
Base Model 2 = LinearSVC(C = 10, loss = hinge, max_iter = 2000, fit_intercept = True), Akurasi = 0.8244993313131656
Base Model 3 = RandomForestClassifier(n_estimators = 200, max_depth = 16, min_samples_leaf = 5, n_bins = 15, random_state = 42), Akurasi = 0.730341453505104
Meta Model   = LogisticRegression(C = 0.1 penalty = l1, max_iter = 100, linesearch_max_iter = 50), Akurasi = 0.8244146874100658
Batch Test   = 2
===== Juara 13 =====
Paket Data   = Balance
tf_idf       = TfidfVectorizer(ngram_range = (1, 2),max_features = 10000,max_df = 0.9,min_df = 0.01,binary = False)
Imbalancer   = Tanpa Imbalancer
Base Model 1 = MultinomialNB(alpha = 0.1), Akurasi = 0.7908279866601209
Base Model 2 = LinearSVC(C = 10, loss = hinge, max_iter = 2000, fit_intercept = True), Akurasi = 0.8244654737519257
Base Model 3 = RandomForestClassifier(n_estimators = 200, max_depth = 16, min_samples_leaf = 5, n_bins = 32, random_state = 42), Akurasi = 0.7292918691066682
Meta Model   = LogisticRegression(C = 0.01 penalty = l1, max_iter = 100, linesearch_max_iter = 50), Akurasi = 0.824380829848826
Batch Test   = 2
===== Juara 14 =====
Paket Data   = Balance
tf_idf       = TfidfVectorizer(ngram_range = (1, 2),max_features = 10000,max_df = 0.9,min_df = 0.01,binary = False)
Imbalancer   = Tanpa Imbalancer
Base Model 1 = MultinomialNB(alpha = 0.1), Akurasi = 0.7908279866601209
Base Model 2 = LinearSVC(C = 10, loss = hinge, max_iter = 2000, fit_intercept = True), Akurasi = 0.8244654737519257
Base Model 3 = RandomForestClassifier(n_estimators = 200, max_depth = 16, min_samples_leaf = 5, n_bins = 32, random_state = 42), Akurasi = 0.7292918691066682
Meta Model   = LogisticRegression(C = 0.1 penalty = l1, max_iter = 100, linesearch_max_iter = 50), Akurasi = 0.824380829848826
Batch Test   = 2
===== Juara 15 =====
Paket Data   = Balance
tf_idf       = TfidfVectorizer(ngram_range = (1, 2),max_features = 10000,max_df = 0.9,min_df = 0.01,binary = False)
Imbalancer   = Tanpa Imbalancer
Base Model 1 = MultinomialNB(alpha = 0.1), Akurasi = 0.7908279866601209
Base Model 2 = LinearSVC(C = 10, loss = hinge, max_iter = 2000, fit_intercept = True), Akurasi = 0.8244654737519257
Base Model 3 = RandomForestClassifier(n_estimators = 200, max_depth = 16, min_samples_leaf = 3, n_bins = 15, random_state = 42), Akurasi = 0.73132332278106
Meta Model   = LogisticRegression(C = 0.01 penalty = l1, max_iter = 100, linesearch_max_iter = 50), Akurasi = 0.824363901068206
Batch Test   = 2
===== Juara 16 =====
Paket Data   = Balance
tf_idf       = TfidfVectorizer(ngram_range = (1, 2),max_features = 10000,max_df = 0.9,min_df = 0.01,binary = False)
Imbalancer   = Tanpa Imbalancer
Base Model 1 = MultinomialNB(alpha = 0.1), Akurasi = 0.7908279866601209
Base Model 2 = LinearSVC(C = 10, loss = hinge, max_iter = 2000, fit_intercept = True), Akurasi = 0.8244654737519257
Base Model 3 = RandomForestClassifier(n_estimators = 200, max_depth = 16, min_samples_leaf = 3, n_bins = 15, random_state = 42), Akurasi = 0.73132332278106
Meta Model   = LogisticRegression(C = 0.1 penalty = l1, max_iter = 100, linesearch_max_iter = 50), Akurasi = 0.824363901068206
Batch Test   = 2
===== Juara 17 =====
Paket Data   = Balance
tf_idf       = TfidfVectorizer(ngram_range = (1, 2),max_features = 10000,max_df = 0.9,min_df = 0.01,binary = False)
Imbalancer   = Tanpa Imbalancer
Base Model 1 = MultinomialNB(alpha = 0.1), Akurasi = 0.7908279866601209
Base Model 2 = LinearSVC(C = 10, loss = hinge, max_iter = 2000, fit_intercept = True), Akurasi = 0.8244654737519257
Base Model 3 = RandomForestClassifier(n_estimators = 200, max_depth = 16, min_samples_leaf = 5, n_bins = 64, random_state = 42), Akurasi = 0.730341453505104
Meta Model   = LogisticRegression(C = 0.01 penalty = l1, max_iter = 100, linesearch_max_iter = 50), Akurasi = 0.8243469722875861
Batch Test   = 2
===== Juara 18 =====
Paket Data   = Balance
tf_idf       = TfidfVectorizer(ngram_range = (1, 2),max_features = 10000,max_df = 0.9,min_df = 0.01,binary = False)
Imbalancer   = Tanpa Imbalancer
Base Model 1 = MultinomialNB(alpha = 0.1), Akurasi = 0.7908279866601209
Base Model 2 = LinearSVC(C = 10, loss = hinge, max_iter = 2000, fit_intercept = True), Akurasi = 0.8244654737519257
Base Model 3 = RandomForestClassifier(n_estimators = 200, max_depth = 16, min_samples_leaf = 5, n_bins = 64, random_state = 42), Akurasi = 0.730341453505104
Meta Model   = LogisticRegression(C = 0.1 penalty = l1, max_iter = 100, linesearch_max_iter = 50), Akurasi = 0.8243469722875861
Batch Test   = 2
===== Juara 19 =====
Paket Data   = Balance
tf_idf       = TfidfVectorizer(ngram_range = (1, 2),max_features = 10000,max_df = 0.9,min_df = 0.01,binary = False)
Imbalancer   = Tanpa Imbalancer
Base Model 1 = MultinomialNB(alpha = 0.1), Akurasi = 0.7908279866601209
Base Model 2 = LinearSVC(C = 10, loss = hinge, max_iter = 2000, fit_intercept = True), Akurasi = 0.8244654737519257
Base Model 3 = RandomForestClassifier(n_estimators = 200, max_depth = 16, min_samples_leaf = 3, n_bins = 32, random_state = 42), Akurasi = 0.7290210086167493
Meta Model   = LogisticRegression(C = 0.01 penalty = l1, max_iter = 100, linesearch_max_iter = 50), Akurasi = 0.8243300435069661
Batch Test   = 2
===== Juara 20 =====
Paket Data   = Balance
tf_idf       = TfidfVectorizer(ngram_range = (1, 2),max_features = 10000,max_df = 0.9,min_df = 0.01,binary = False)
Imbalancer   = Tanpa Imbalancer
Base Model 1 = MultinomialNB(alpha = 0.1), Akurasi = 0.7908279866601209
Base Model 2 = LinearSVC(C = 10, loss = hinge, max_iter = 2000, fit_intercept = True), Akurasi = 0.8244654737519257
Base Model 3 = RandomForestClassifier(n_estimators = 200, max_depth = 16, min_samples_leaf = 3, n_bins = 32, random_state = 42), Akurasi = 0.7290210086167493
Meta Model   = LogisticRegression(C = 0.1 penalty = l1, max_iter = 100, linesearch_max_iter = 50), Akurasi = 0.8243300435069661
Batch Test   = 2
===== Juara 21 =====
Paket Data   = Balance
tf_idf       = TfidfVectorizer(ngram_range = (1, 2),max_features = 10000,max_df = 0.9,min_df = 0.01,binary = False)
Imbalancer   = Tanpa Imbalancer
Base Model 1 = MultinomialNB(alpha = 0.1), Akurasi = 0.7908279866601209
Base Model 2 = LinearSVC(C = 10, loss = hinge, max_iter = 2000, fit_intercept = True), Akurasi = 0.8244654737519257
Base Model 3 = RandomForestClassifier(n_estimators = 200, max_depth = 16, min_samples_leaf = 3, n_bins = 64, random_state = 42), Akurasi = 0.7287670769074504
Meta Model   = LogisticRegression(C = 0.01 penalty = l1, max_iter = 100, linesearch_max_iter = 50), Akurasi = 0.8243300435069661
Batch Test   = 2
===== Juara 22 =====
Paket Data   = Balance
tf_idf       = TfidfVectorizer(ngram_range = (1, 2),max_features = 10000,max_df = 0.9,min_df = 0.01,binary = False)
Imbalancer   = Tanpa Imbalancer
Base Model 1 = MultinomialNB(alpha = 0.1), Akurasi = 0.7908279866601209
Base Model 2 = LinearSVC(C = 10, loss = hinge, max_iter = 2000, fit_intercept = True), Akurasi = 0.8244654737519257
Base Model 3 = RandomForestClassifier(n_estimators = 200, max_depth = 16, min_samples_leaf = 3, n_bins = 64, random_state = 42), Akurasi = 0.7287670769074504
Meta Model   = LogisticRegression(C = 0.1 penalty = l1, max_iter = 100, linesearch_max_iter = 50), Akurasi = 0.8243300435069661
Batch Test   = 2
===== Juara 23 =====
Paket Data   = Balance
tf_idf       = TfidfVectorizer(ngram_range = (1, 2),max_features = 10000,max_df = 0.9,min_df = 0.01,binary = False)
Imbalancer   = Tanpa Imbalancer
Base Model 1 = MultinomialNB(alpha = 0.1), Akurasi = 0.7908279866601209
Base Model 2 = LinearSVC(C = 10, loss = hinge, max_iter = 2000, fit_intercept = True), Akurasi = 0.8244654737519257
Base Model 3 = RandomForestClassifier(n_estimators = 200, max_depth = 16, min_samples_leaf = 5, n_bins = 15, random_state = 42), Akurasi = 0.730341453505104
Meta Model   = LogisticRegression(C = 0.01 penalty = l1, max_iter = 100, linesearch_max_iter = 50), Akurasi = 0.8243300435069661
Batch Test   = 2
===== Juara 24 =====
Paket Data   = Balance
tf_idf       = TfidfVectorizer(ngram_range = (1, 2),max_features = 10000,max_df = 0.9,min_df = 0.01,binary = False)
Imbalancer   = Tanpa Imbalancer
Base Model 1 = MultinomialNB(alpha = 0.1), Akurasi = 0.7908279866601209
Base Model 2 = LinearSVC(C = 10, loss = hinge, max_iter = 2000, fit_intercept = True), Akurasi = 0.8244654737519257
Base Model 3 = RandomForestClassifier(n_estimators = 200, max_depth = 16, min_samples_leaf = 5, n_bins = 15, random_state = 42), Akurasi = 0.730341453505104
Meta Model   = LogisticRegression(C = 0.1 penalty = l1, max_iter = 100, linesearch_max_iter = 50), Akurasi = 0.8243300435069661
Batch Test   = 2
===== Juara 25 =====
Paket Data   = Balance
tf_idf       = TfidfVectorizer(ngram_range = (1, 2),max_features = 10000,max_df = 0.9,min_df = 0.01,binary = False)
Imbalancer   = Tanpa Imbalancer
Base Model 1 = MultinomialNB(alpha = 10), Akurasi = 0.7897445447004452
Base Model 2 = LinearSVC(C = 10, loss = hinge, max_iter = 2000, fit_intercept = True), Akurasi = 0.824363901068206
Base Model 3 = RandomForestClassifier(n_estimators = 200, max_depth = 16, min_samples_leaf = 3, n_bins = 15, random_state = 42), Akurasi = 0.73132332278106
Meta Model   = LogisticRegression(C = 0.01 penalty = l1, max_iter = 100, linesearch_max_iter = 50), Akurasi = 0.8242792571651064
Batch Test   = 2
===== Juara 26 =====
Paket Data   = Balance
tf_idf       = TfidfVectorizer(ngram_range = (1, 2),max_features = 10000,max_df = 0.9,min_df = 0.01,binary = False)
Imbalancer   = Tanpa Imbalancer
Base Model 1 = MultinomialNB(alpha = 10), Akurasi = 0.7897445447004452
Base Model 2 = LinearSVC(C = 10, loss = hinge, max_iter = 2000, fit_intercept = True), Akurasi = 0.824363901068206
Base Model 3 = RandomForestClassifier(n_estimators = 200, max_depth = 16, min_samples_leaf = 3, n_bins = 15, random_state = 42), Akurasi = 0.73132332278106
Meta Model   = LogisticRegression(C = 0.1 penalty = l1, max_iter = 100, linesearch_max_iter = 50), Akurasi = 0.8242792571651064
Batch Test   = 2
===== Juara 27 =====
Paket Data   = Balance
tf_idf       = TfidfVectorizer(ngram_range = (1, 2),max_features = 10000,max_df = 0.9,min_df = 0.01,binary = False)
Imbalancer   = Tanpa Imbalancer
Base Model 1 = MultinomialNB(alpha = 10), Akurasi = 0.7897445447004452
Base Model 2 = LinearSVC(C = 10, loss = hinge, max_iter = 2000, fit_intercept = True), Akurasi = 0.824363901068206
Base Model 3 = RandomForestClassifier(n_estimators = 200, max_depth = 16, min_samples_leaf = 5, n_bins = 64, random_state = 42), Akurasi = 0.730341453505104
Meta Model   = LogisticRegression(C = 0.01 penalty = l1, max_iter = 100, linesearch_max_iter = 50), Akurasi = 0.8242792571651064
Batch Test   = 2
===== Juara 28 =====
Paket Data   = Balance
tf_idf       = TfidfVectorizer(ngram_range = (1, 2),max_features = 10000,max_df = 0.9,min_df = 0.01,binary = False)
Imbalancer   = Tanpa Imbalancer
Base Model 1 = MultinomialNB(alpha = 10), Akurasi = 0.7897445447004452
Base Model 2 = LinearSVC(C = 10, loss = hinge, max_iter = 2000, fit_intercept = True), Akurasi = 0.824363901068206
Base Model 3 = RandomForestClassifier(n_estimators = 200, max_depth = 16, min_samples_leaf = 5, n_bins = 64, random_state = 42), Akurasi = 0.730341453505104
Meta Model   = LogisticRegression(C = 0.1 penalty = l1, max_iter = 100, linesearch_max_iter = 50), Akurasi = 0.8242792571651064
Batch Test   = 2
===== Juara 29 =====
Paket Data   = Balance
tf_idf       = TfidfVectorizer(ngram_range = (1, 2),max_features = 10000,max_df = 0.9,min_df = 0.01,binary = False)
Imbalancer   = Tanpa Imbalancer
Base Model 1 = MultinomialNB(alpha = 10), Akurasi = 0.7897445447004452
Base Model 2 = LinearSVC(C = 10, loss = hinge, max_iter = 2000, fit_intercept = True), Akurasi = 0.824363901068206
Base Model 3 = RandomForestClassifier(n_estimators = 200, max_depth = 16, min_samples_leaf = 3, n_bins = 64, random_state = 42), Akurasi = 0.7287670769074504
Meta Model   = LogisticRegression(C = 0.01 penalty = l1, max_iter = 100, linesearch_max_iter = 50), Akurasi = 0.8242623283844864
Batch Test   = 2
===== Juara 30 =====
Paket Data   = Balance
tf_idf       = TfidfVectorizer(ngram_range = (1, 2),max_features = 10000,max_df = 0.9,min_df = 0.01,binary = False)
Imbalancer   = Tanpa Imbalancer

In [19]:
import pickle

nama_file = "Naive_Bayes_B1.pkl"
with open(nama_file, 'wb') as f:
    pickle.dump(list_top_20_p2[0].base_model_1[0], f)
nama_file = "Support_Vector_Machine_B2.pkl"
with open(nama_file, 'wb') as f:
    pickle.dump(list_top_20_p2[0].base_model_2[0], f)
nama_file = "Random_Forest_B3.pkl"
with open(nama_file, 'wb') as f:
    pickle.dump(list_top_20_p2[0].base_model_3[0], f)
nama_file = "Logistic_Linear_Meta.pkl"
with open(nama_file, 'wb') as f:
    pickle.dump(list_top_20_p2[0].meta_model[0], f)
nama_file = "Tf_Idf.pkl"
with open(nama_file, 'wb') as f:
    pickle.dump(list_top_20_p2[0].tf_idf_model[0], f)