## Klasifikasi Flop, Below Average, Average, Hits

In [6]:
import pandas as pd

data = pd.read_csv("Hasil_Klasifikasi_Review.csv")
data.head()

,review_id,reviewer,movie,rating,review_summary,review_date,spoiler_tag,review_detail,helpful,label_komen
0,rw5704482,raeldor-96879,After Life (2019– ),9.0,Very Strong Season 2,3 May 2020,0,"I enjoyed the first season, but I must say I t...","['1', '1']",1
1,rw5704483,dosleeb,The Valhalla Murders (2019– ),6.0,Icelandic detectives?,3 May 2020,0,I know Iceland is a small country and police d...,"['2', '2']",0
2,rw5704484,brightconscious,Special OPS (2020– ),7.0,Nothing special,3 May 2020,0,"Except K K , no other actor looks comfortable ...","['0', '0']",0
3,rw5704485,gasconyway,#BlackAF (2020– ),8.0,Good but,3 May 2020,0,I'm guessing that as a 62 year old white woman...,"['5', '9']",1
4,rw5704487,mmason-15867,The Droving (2020),2.0,An honest review,3 May 2020,0,Here's the truth. There's not much to this mov...,"['26', '41']",0

In [7]:
dict_rating_label = {}

for i in range(data.shape[0]) :
    if data["movie"][i] not in dict_rating_label :
        dict_rating_label[data["movie"][i]] = [data["rating"][i],data["label_komen"][i],1]
    else :
        dict_rating_label[data["movie"][i]][0] += data["rating"][i]
        dict_rating_label[data["movie"][i]][1] += data["label_komen"][i]
        dict_rating_label[data["movie"][i]][2] += 1
        
for i in dict_rating_label :
    dict_rating_label[i][0] /= dict_rating_label[i][2]
    dict_rating_label[i][1] /= dict_rating_label[i][2]

dict_hasil = {"movie" : [], "avg_rating" : [], "avg_sentiment" : [], "klasifikasi" : []}

for i in dict_rating_label :
    dict_hasil["movie"].append(i)
    dict_hasil["avg_rating"].append(dict_rating_label[i][0])
    dict_hasil["avg_sentiment"].append(dict_rating_label[i][1])
    if dict_rating_label[i][1] < 0.5 :
        if dict_rating_label[i][0] <= 5 :
            klasifikasi = "Flop"
        else :
            klasifikasi = "Average"
    else :
        if dict_rating_label[i][0] <= 5 :
            klasifikasi = "Below Average"
        else :
            klasifikasi = "Hits"
    dict_hasil["klasifikasi"].append(klasifikasi)
    
df_hasil = pd.DataFrame(dict_hasil)
df_hasil.head()

                           movie  avg_rating  avg_sentiment klasifikasi
0            After Life (2019– )    8.996479       0.841549        Hits
1  The Valhalla Murders (2019– )    5.925532       0.404255     Average
2           Special OPS (2020– )    8.708625       0.827506        Hits
3              #BlackAF (2020– )    7.181818       0.636364        Hits
4             The Droving (2020)    6.928571       0.761905        Hits

In [8]:
df_hasil.to_csv("Klasifikasi 4 Kategori per Film.csv", index=False)